### PR TITLE
added notes for the beginners guide to react

### PR DESCRIPTION
**Pull request by lsminter**
Added and formatted The Beginners Guide to React course notes. Holding off on moving ET's until we come to a decision on how to store them.

### CODE REVIEW

**Comment by laurosilvacom** [comment]
Great @lsminter! I think we can move on the next steps 

- [ ] Delete the `.DS_Store` file. 
- [ ] Delete all-contributors content from README.md
- [ ] Add the contributors to the monorepo's README.md once this PR is merged
- [ ] Add a link/message in the individual repository pointing to the monorepo
- [ ] Archived the old repository

**Comment by laurosilvacom** [comment]
@all-contributors please add @lsminter  for review

**Comment by laurosilvacom** [comment]
@lsminter what do you think about adding the all-contributors using the bot instead of manually? Similar to the above PR.

**Comment by lsminter** [comment]
@all-contributors please add @laurosilvacom for review

**Comment by laurosilvacom** [comment]
@all-contributors please add @rosaxny for content

**Comment by laurosilvacom** [comment]
@all-contributors please add @koji for content

**Comment by laurosilvacom** [comment]
@all-contributors please add @lsminter for review

**Comment by laurosilvacom** [comment]
@all-contributors please add @plug-n-play for content

**Comment by laurosilvacom** [comment]
@all-contributors please add @mgrinthal for content

**Comment by laurosilvacom** [comment]
@all-contributors please add @thaycacac for content

**Comment by laurosilvacom** [comment]
@all-contributors please add @tomByrer for content

**Pull request merged**
